specVersion: 0.2.0
name: salp-confirm-kusama-subql
version: 1.0.0
description: ''
repository: https://github.com/bifrost-finance/salp-confirm-kusama-subql.git
schema:
  file: ./schema.graphql
network:
  genesisHash: '0x91b171bb158e2d3848fa23a9f1c25182fb8e20313b2c1eb49219da7a70ce90c3'
  endpoint: ws://172.19.0.6:29944
dataSources:
  - kind: substrate/Runtime
    startBlock: 12073229
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: parasUmp
          kind: substrate/BlockHandler
        - handler: handleParasUmpUpwardMessagesReceived
          kind: substrate/EventHandler
          filter:
            module: ump
            method: UpwardMessagesReceived
        - handler: handleUmpExecutedUpward
          kind: substrate/EventHandler
          filter:
            module: ump
            method: ExecutedUpward
        - handler: handleUmpWeightExhausted
          kind: substrate/EventHandler
          filter:
            module: ump
            method: WeightExhausted
        - handler: handleUmpInvalidFormat
          kind: substrate/EventHandler
          filter:
            module: ump
            method: InvalidFormat
        - handler: handleUmpUnsupportedVersion
          kind: substrate/EventHandler
          filter:
            module: ump
            method: UnsupportedVersion
