specVersion: 0.0.1
description: ''
repository: https://github.com/bifrost-finance/salp-confirm-kusama-subql.git
schema: ./schema.graphql
network:
    # endpoint: 'wss://kusama-rpc.polkadot.io'
    endpoint: 'wss://kusama-rpc.testnet.liebi.com/ws'
    # endpoint: 'wss://kusama-rpc.liebi.com/ws'
  # dictionary: https://api.subquery.network/sq/subquery/dictionary-polkadot
dataSources:
  - name: main
    kind: substrate/Runtime
    startBlock: 1
    # startBlock: 8324700
    mapping:
      handlers:
        # - handler: handleBlock
        #   kind: substrate/BlockHandler
        # - handler: handleEvent
        #   kind: substrate/EventHandler
        #   filter:
        #     module: balances
        #     method: Deposit
        # - handler: handleCall
        #   kind: substrate/CallHandler
        - handler: parasUmp
          kind: substrate/BlockHandler
        - handler: handleParasUmpUpwardMessagesReceived
          kind: substrate/EventHandler
          filter:
            module: parasUmp
            method: UpwardMessagesReceived
        # - handler: handleContributed
        #   kind: substrate/EventHandler
        #   filter:
        #     module: crowdloan
        #     method: Contributed
        # - handler: handleMemo
        #   kind: substrate/EventHandler
        #   filter:
        #     module: crowdloan
        #     method: MemoUpdated
        # - handler: handleSystemExtrinsicFailed
        #   kind: substrate/EventHandler
        #   filter:
        #     module: system
        #     method: ExtrinsicFailed