specVersion: 0.2.0
name: salp-confirm-kusama-subql
version: 1.0.0
description: ''
repository: https://github.com/bifrost-finance/salp-confirm-kusama-subql.git
schema:
  file: ./schema.graphql
network:
  genesisHash: '0xb0a8d493285c2df73290dfb7e61f870f17b41801197a149ca93654499ea3dafe'
  endpoint: wss://kusama-rpc.liebi.com/ws
dataSources:
  - kind: substrate/Runtime
    startBlock: 9246356
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: parasUmp
          kind: substrate/BlockHandler
        - handler: handleParasUmpUpwardMessagesReceived
          kind: substrate/EventHandler
          filter:
            module: ump
            method: UpwardMessagesReceived
        - handler: handleUmpExecutedUpward
          kind: substrate/EventHandler
          filter:
            module: ump
            method: ExecutedUpward
        - handler: handleUmpWeightExhausted
          kind: substrate/EventHandler
          filter:
            module: ump
            method: WeightExhausted
        - handler: handleUmpInvalidFormat
          kind: substrate/EventHandler
          filter:
            module: ump
            method: InvalidFormat
        - handler: handleUmpUnsupportedVersion
          kind: substrate/EventHandler
          filter:
            module: ump
            method: UnsupportedVersion
