specVersion: 0.0.1
description: ''
repository: https://github.com/bifrost-finance/salp-confirm-kusama-subql.git
schema: ./schema.graphql
network:
    endpoint: 'wss://kusama-rpc.polkadot.io'
  # dictionary: https://api.subquery.network/sq/subquery/dictionary-polkadot
dataSources:
  - name: main
    kind: substrate/Runtime
    startBlock: 8324700
    mapping:
      handlers:
        - handler: handleBlock
          kind: substrate/BlockHandler
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: balances
            method: Deposit
        - handler: handleCall
          kind: substrate/CallHandler
        # - handler: parasUmp
        #   kind: substrate/BlockHandler
        - handler: handleContributed
          kind: substrate/EventHandler
          filter:
            module: crowdloan
            method: Contributed
        - handler: handleMemo
          kind: substrate/EventHandler
          filter:
            module: crowdloan
            method: MemoUpdated