specVersion: 0.0.1
description: ''
repository: https://github.com/bifrost-finance/salp-confirm-kusama-subql.git
schema: ./schema.graphql
network:
    endpoint: 'wss://kusama-rpc.polkadot.io'
dataSources:
  - name: main
    kind: substrate/Runtime
    startBlock: 11171248
    mapping:
      handlers:
        - handler: parasUmp
          kind: substrate/BlockHandler
        - handler: handleParasUmpUpwardMessagesReceived
          kind: substrate/EventHandler
          filter:
            module: ump
            method: UpwardMessagesReceived
        - handler: handleUmpExecutedUpward
          kind: substrate/EventHandler
          filter:
            module: ump
            method: ExecutedUpward
        - handler: handleUmpWeightExhausted
          kind: substrate/EventHandler
          filter:
            module: ump
            method: WeightExhausted
        - handler: handleUmpInvalidFormat
          kind: substrate/EventHandler
          filter:
            module: ump
            method: InvalidFormat
        - handler: handleUmpUnsupportedVersion
          kind: substrate/EventHandler
          filter:
            module: ump
            method: UnsupportedVersion
        - handler: democracy
          kind: substrate/BlockHandler
        - handler: council
          kind: substrate/BlockHandler