specVersion: 0.0.1
description: ''
repository: https://github.com/bifrost-finance/salp-confirm-kusama-subql.git
schema: ./schema.graphql
network:
    # endpoint: 'wss://kusama-rpc.polkadot.io'
    endpoint: 'wss://kusama-rpc.testnet.liebi.com/ws'
    # endpoint: 'wss://kusama-rpc.liebi.com/ws'
  # dictionary: https://api.subquery.network/sq/subquery/dictionary-polkadot
dataSources:
  - name: main
    kind: substrate/Runtime
    startBlock: 1
    # startBlock: 8324700
    mapping:
      handlers:
        - handler: parasUmp
          kind: substrate/BlockHandler
        - handler: handleParasUmpUpwardMessagesReceived
          kind: substrate/EventHandler
          filter:
            module: ump
            method: UpwardMessagesReceived
        # - handler: handleContributed
        #   kind: substrate/EventHandler
        #   filter:
        #     module: crowdloan
        #     method: Contributed
        # - handler: handleSystemExtrinsicFailed
        #   kind: substrate/EventHandler
        #   filter:
        #     module: system
        #     method: ExtrinsicFailed
        - handler: handleUmpExecutedUpward
          kind: substrate/EventHandler
          filter:
            module: ump
            method: ExecutedUpward
        - handler: handleUmpWeightExhausted
          kind: substrate/EventHandler
          filter:
            module: ump
            method: WeightExhausted
        - handler: handleUmpInvalidFormat
          kind: substrate/EventHandler
          filter:
            module: ump
            method: InvalidFormat
        - handler: handleUmpUnsupportedVersion
          kind: substrate/EventHandler
          filter:
            module: ump
            method: UnsupportedVersion